### ISSUE TITLE
Spanish Worlds

### ISSUE THREAD

**Issue by AlfonsoBR** [ngagesdk/wordle#22]
i Wolud like to add Spanish Support, first obtaitning other WORDLE spanish list, but How can i start to implementing it on "wordlist_es.c", What is its structure?

**Comment by mupfdev** [comment]
Unfortunately the process it not that straightforward. However, I am certainly willing to assist!

A few questions:

- Does your word list contain umlauts or special characters?
- If so, does the language introduce new umlauts (in comparison to the other available languages)?
- Can you provide a plain list of the words (preferably as a char array)?

Regards, Michael

**Comment by mupfdev** [comment]
I also suggest to create a fork of the project and a new branch called `spanish` or something.

**Comment by mupfdev** [comment]
Since I haven't heard back from you, I consider this case closed for now. Just re-open the issue if you want this list integrated.
